[project]
name = "tasks-api"
version = "1.0.0"
requires-python = ">=3.14"

dependencies = [
    "fastapi>=0.140.0",
    "uvicorn>=0.30.0",
    "shared",
    "sqlalchemy>=2.0.51",
    "passlib>=1.7.4",
    "bcrypt==4.0.1",
    "python-multipart>=0.0.32",
    "python-jose[cryptography]>=3.5.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
tasks-api = "tasks_api.main:main"

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
