"""add phone number to user

Revision ID: dd56d5669ec7
Revises: 01b9df10e504
Create Date: 2026-08-19 19:35:59.984713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd56d5669ec7'
down_revision: Union[str, None] = '01b9df10e504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
